// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sixth-front-variants/SixthFrontEditorial.tsx": () => import("../components/mockups/sixth-front-variants/SixthFrontEditorial.tsx"),
  "./components/mockups/sixth-front-variants/SixthFrontFieldGuide.tsx": () => import("../components/mockups/sixth-front-variants/SixthFrontFieldGuide.tsx"),
  "./components/mockups/sixth-front-variants/SixthFrontIndex.tsx": () => import("../components/mockups/sixth-front-variants/SixthFrontIndex.tsx"),
  "./components/mockups/sixth-front-variants/SixthFrontPolished.tsx": () => import("../components/mockups/sixth-front-variants/SixthFrontPolished.tsx")
};
